# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: bridge-indexer
description: SP1 bridge indexer
unordered_multichain_mode: true

contracts:
  - name: Bridge
    handler: src/EventHandlers.ts
    events:
      - event: "Deposit(address indexed who, uint256 indexed amount, address indexed token, address to,uint256 sourceChain,uint256 destinationChain)"
        field_selection:
          transaction_fields:
            - "hash"
      - event: "Claimed(address indexed who, uint256 indexed amount, address indexed token,address to,uint256 sourceChain,bytes publicInputs,bytes proofBytes)"
        field_selection:
          transaction_fields:
            - "hash"

networks:
  - id: 1 # Ethereum Mainnet
    rpc_config:
      url: http://host.docker.internal:8545
    start_block: 23815587
    contracts:
      - name: Bridge
        address: "0xF1a7a5060f22edA40b1A94a858995fa2bcf5E75A"
  - id: 8453 # Base Mainnet
    rpc_config:
      url: http://host.docker.internal:8546
    start_block: 38276600
    contracts:
      - name: Bridge
        address: "0xCfecDD44270Fa180d9EC79d7A56f1A8bC9363Ee8"
