[package]
name = "bridge-program"
edition.workspace = true
license.workspace = true
authors.workspace = true
exclude.workspace = true
version.workspace = true

[lib]
name = "bridge_program"
path = "src/lib.rs"

[[bin]]
name = "bridge-program"
path = "src/main.rs"
required-features = ["zkvm"]

[features]
default = ["zkvm"]
zkvm = ["sp1-zkvm"]

[dependencies]
sp1-zkvm         = { workspace = true, optional = true }
serde            = { workspace = true }
alloy-primitives = { workspace = true }
alloy-sol-types  = { workspace = true }
alloy-rlp        = { workspace = true }
alloy-trie       = { workspace = true }
sha3             = { workspace = true }
sp1-types        = { workspace = true }
