import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import {
  loadRuntimeConfig as loadSelectedRuntimeConfig,
  runtimeConfigPath,
  type RuntimeChainConfig,
  type RuntimeConfig,
} from "./runtime-config-lib.ts";

export const INDEXER_CONFIG_PATH = path.join("indexer", "config.yaml");

export interface DeployAddresses {
  bridge: string;
  validatorManager: string;
}

function rpcUrl(sourceUrl: string): string {
  const parsedUrl = new URL(sourceUrl);
  if (process.env.INDEXER_LOCAL) {
    parsedUrl.hostname = "127.0.0.1";
    return parsedUrl.toString();
  }
  parsedUrl.hostname = "host.docker.internal";
  return parsedUrl.toString();
}

function loadDeploy(runtimeConfig: RuntimeConfig, chainId: number): DeployAddresses {
  const deployPath = path.join(runtimeConfig.deployments_dir, `${chainId}.json`);
  if (!fs.existsSync(deployPath)) {
    throw new Error(`${deployPath} not found - run \`make deploy-local\` first`);
  }

  const raw = fs.readFileSync(deployPath, "utf8");
  const parsed = JSON.parse(raw) as Partial<DeployAddresses>;

  if (!parsed.bridge || !parsed.validatorManager) {
    throw new Error(`missing bridge/validatorManager in ${deployPath}`);
  }

  return {
    bridge: parsed.bridge,
    validatorManager: parsed.validatorManager,
  };
}

function loadRuntimeConfig(): RuntimeConfig {
  const configPath = runtimeConfigPath();
  if (!fs.existsSync(configPath)) {
    throw new Error(`${configPath} not found`);
  }

  return loadSelectedRuntimeConfig(configPath);
}

function getLatestBlock(rpcUrl: string): number {
  const result = spawnSync("cast", ["block-number", "--rpc-url", rpcUrl], { encoding: "utf8" });
  if (result.error || result.status !== 0) return 0;
  const n = parseInt(result.stdout.trim(), 10);
  return isNaN(n) ? 0 : n;
}

function buildNetworkConfig(chain: RuntimeChainConfig, deploy: DeployAddresses): string {
  const startBlock = getLatestBlock(chain.rpc_url);
  return `  - id: ${chain.id}
    rpc_config:
      url: ${rpcUrl(chain.rpc_url)}
    start_block: ${startBlock}
    contracts:
      - name: Bridge
        address: "${deploy.bridge}"
      - name: ValidatorManager
        address: "${deploy.validatorManager}"`;
}

function buildConfig(runtimeConfig: RuntimeConfig): string {
  const networkConfig = runtimeConfig.chains
    .map((chain) => buildNetworkConfig(chain, loadDeploy(runtimeConfig, chain.id)))
    .join("\n\n");

  return `# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
# AUTO-GENERATED by scripts/update-indexer-config.ts - do not edit by hand.
# Re-run \`make update-indexer-config\` after \`make deploy-local\`.
name: bridge-indexer
description: SP1 bridge indexer
unordered_multichain_mode: true

contracts:
  - name: Bridge
    handler: src/EventHandlers.ts
    events:
      - event: "Deposit(address indexed who, uint256 amount, address indexed token, address to, uint256 sourceChain, uint256 destinationChain, uint256 depositIndex, bytes32 indexed depositRoot)"
        field_selection:
          transaction_fields:
            - "hash"
      - event: "Claimed(address indexed claimer, uint256 indexed amount, address indexed token, address recipient, uint256 sourceChain, uint256 depositIndex, uint256 claimIndex, bytes32 sourceRoot, bytes32 claimRoot, uint256 destinationChain)"
        field_selection:
          transaction_fields:
            - "hash"

  - name: ValidatorManager
    handler: src/EventHandlers.ts
    events:
      - event: "AttestationSubmitted(address indexed validator, uint256 indexed sourceChainId, bytes32 indexed bridgeRoot, uint256 blockNumber, bytes32 stateRoot, uint256 timestamp)"
        field_selection:
          transaction_fields:
            - "hash"

networks:
${networkConfig}
`;
}

export function generateIndexerConfig(): string {
  return buildConfig(loadRuntimeConfig());
}

export function updateIndexerConfig(): void {
  const runtimeConfig = loadRuntimeConfig();
  const output = buildConfig(runtimeConfig);
  fs.writeFileSync(INDEXER_CONFIG_PATH, output, "utf8");

  console.log(`Updated ${INDEXER_CONFIG_PATH} with local deployment addresses:`);
  for (const chain of runtimeConfig.chains) {
    const deploy = loadDeploy(runtimeConfig, chain.id);
    console.log(`  Chain ${chain.id} bridge: ${deploy.bridge}`);
    console.log(`  Chain ${chain.id} validatorManager: ${deploy.validatorManager}`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    updateIndexerConfig();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
