[package]
name = "chain-manager"
edition.workspace = true
license.workspace = true
authors.workspace = true
exclude.workspace = true
version.workspace = true

[dependencies]
jsonrpsee = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
alloy-consensus = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-network = { workspace = true }
alloy-node-bindings = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
once_cell = { workspace = true }
alloy-trie = { workspace = true }
alloy-rlp = { workspace = true }
alloy-eips = { workspace = true }
thiserror = { workspace = true }
eyre = { workspace = true }
jsonrpsee-core = { workspace = true }
dashmap = { workspace = true }
serial_test = { workspace = true }
reth-trie = { workspace = true }
reth-trie-common = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["full"] }
dotenv = { workspace = true }
validator-utils = { workspace = true }

[lints]
workspace = true
[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
